# Generated by Django 5.2.4 on 2025-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
